import{a as S,S as v,i}from"./assets/vendor-BgmC94F3.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();async function m(e,o=1){const s="53051578-6e8f28ab3f0bf52fa1c2ada27",n="https://pixabay.com/api/",t={key:s,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:o};return(await S.get(n,{params:t})).data}const P=new v(".gallery a",{captionsData:"alt",captionDelay:250}),h=document.querySelector(".loader"),p=document.querySelector(".load-more-button");function M(e){return`
    <li class="gallery-item">
      <a class="gallery-link" href="${e.largeImageURL}">
        <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}" />
      </a>
      <div class="info">
        <p class="info-item"><b>Likes:</b> ${e.likes.toLocaleString()}</p>
        <p class="info-item"><b>Views:</b> ${e.views.toLocaleString()}</p>
        <p class="info-item"><b>Comments:</b> ${e.comments.toLocaleString()}</p>
        <p class="info-item"><b>Downloads:</b> ${e.downloads.toLocaleString()}</p>
      </div>
    </li>
  `}function l(e,o,s=!1){s&&(o.innerHTML="");const n=e.map(M).join("");o.insertAdjacentHTML("beforeend",n),P.refresh()}function y(){h.classList.add("is-visible")}function L(){h.classList.remove("is-visible")}function q(){p.classList.remove("is-hidden")}function f(){p.classList.add("is-hidden")}const g=document.querySelector(".form"),u=document.querySelector(".gallery"),R=document.querySelector(".load-more-button");let a=1,d="",b=0;g.addEventListener("submit",async e=>{e.preventDefault();const o=e.currentTarget.elements["search-text"].value.trim();if(o===""){i.warning({message:"Please enter a search term!",position:"topRight"});return}d=o,a=1,f(),y();try{const s=await m(d,a);if(b=s.totalHits,s.hits.length===0){l([],u,!0),i.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}l(s.hits,u,!0),w()}catch(s){console.error("Error fetching images:",s),i.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{L()}g.reset()});R.addEventListener("click",async()=>{a+=1,y(),f();try{const e=await m(d,a);l(e.hits,u),B(),w()}catch(e){console.error("Error fetching more images:",e),i.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{L()}});function w(){const e=Math.ceil(b/15);a>=e?(f(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):q()}function B(){const e=document.querySelector(".gallery-item");if(e){const o=e.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
